from datetime import datetime, timedelta, timezone
from typing import Dict, List, NamedTuple
from app.models.enums import (
    IncidentStatus,
    Severity,
    SimulationScenario,
    TelemetryEventType,
    TelemetrySource,
)
from app.models.incident import Incident
from app.models.telemetry import TelemetryEvent


class GroundTruth(NamedTuple):
    category: str
    root_cause: str
    affected_service: str
    expected_evidence: List[str]


class ScenarioData(NamedTuple):
    incident_title: str
    incident_description: str
    severity: Severity
    affected_service: str
    ground_truth: GroundTruth
    telemetry_templates: List[Dict]


SCENARIO_DEFINITIONS: Dict[SimulationScenario, ScenarioData] = {
    SimulationScenario.BAD_DEPLOYMENT: ScenarioData(
        incident_title="High HTTP 500 Error Rate in payment-service after deployment",
        incident_description="HTTP error rate spiked to 14.7% shortly after release v1.8.3 was deployed to payment-service instances.",
        severity=Severity.HIGH,
        affected_service="payment-service",
        ground_truth=GroundTruth(
            category="deployment",
            root_cause="Faulty deployment release v1.8.3 introduced unhandled NullPointerExceptions during charge processing.",
            affected_service="payment-service",
            expected_evidence=["DEPLOYMENT_EVENT", "ERROR_RATE_SPIKE", "APPLICATION_EXCEPTION"],
        ),
        telemetry_templates=[
            {
                "offset_seconds": 0,
                "source": TelemetrySource.DEPLOYMENT,
                "event_type": TelemetryEventType.DEPLOYMENT,
                "severity": "INFO",
                "service": "payment-service",
                "message": "Deploying payment-service version v1.8.3 commit 9a8f2c1 by ci-cd-pipeline",
                "metadata": {"version": "v1.8.3", "commit": "9a8f2c1", "deployer": "ci-cd-pipeline"},
            },
            {
                "offset_seconds": 15,
                "source": TelemetrySource.SERVICE,
                "event_type": TelemetryEventType.SERVICE_EVENT,
                "severity": "INFO",
                "service": "payment-service",
                "message": "payment-service instance i-0a1b2c3d started successfully with release v1.8.3",
                "metadata": {"instance_id": "i-0a1b2c3d", "version": "v1.8.3"},
            },
            {
                "offset_seconds": 30,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "INFO",
                "service": "payment-service",
                "message": "payment-service metric: request_rate=150 req/sec, error_rate=0.2%",
                "metadata": {"request_rate": 150, "error_rate": 0.002},
            },
            {
                "offset_seconds": 45,
                "source": TelemetrySource.LOGS,
                "event_type": TelemetryEventType.LOG,
                "severity": "ERROR",
                "service": "payment-service",
                "message": "[ERROR] payment-service: NullPointerException in PaymentGatewayHandler.java:142 processing charge request for customer_9912",
                "metadata": {"exception": "NullPointerException", "class": "PaymentGatewayHandler", "line": 142},
            },
            {
                "offset_seconds": 60,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "ERROR",
                "service": "payment-service",
                "message": "payment-service metric: error_rate increased from 0.2% to 14.7% (threshold: 2.0%)",
                "metadata": {"error_rate": 0.147, "threshold": 0.02},
            },
            {
                "offset_seconds": 75,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "WARN",
                "service": "payment-service",
                "message": "payment-service metric: p99_latency increased from 120ms to 2450ms",
                "metadata": {"p99_latency_ms": 2450, "baseline_ms": 120},
            },
            {
                "offset_seconds": 90,
                "source": TelemetrySource.SERVICE,
                "event_type": TelemetryEventType.ALERT,
                "severity": "CRITICAL",
                "service": "payment-service",
                "message": "ALERT TRIGGERED: HighErrorRate on payment-service (14.7% > 2.0%)",
                "metadata": {"alert_name": "HighErrorRate", "current_value": 0.147},
            },
        ],
    ),
    SimulationScenario.DATABASE_CONNECTION_EXHAUSTION: ScenarioData(
        incident_title="Database Connection Pool Exhaustion on order-db",
        incident_description="Order creation requests failing with HTTP 503 due to database connection pool timeouts on order-db.",
        severity=Severity.CRITICAL,
        affected_service="order-service",
        ground_truth=GroundTruth(
            category="database",
            root_cause="Database connection pool exhaustion on order-db due to unclosed connections under elevated request volume.",
            affected_service="order-service",
            expected_evidence=["TRAFFIC_INCREASE", "DB_POOL_EXHAUSTION", "QUERY_TIMEOUT", "API_ERROR_SPIKE"],
        ),
        telemetry_templates=[
            {
                "offset_seconds": 0,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "INFO",
                "service": "order-service",
                "message": "order-service metric: incoming_request_rate increased from 200 to 850 req/sec",
                "metadata": {"request_rate": 850, "baseline": 200},
            },
            {
                "offset_seconds": 15,
                "source": TelemetrySource.DATABASE,
                "event_type": TelemetryEventType.DATABASE_EVENT,
                "severity": "WARN",
                "service": "order-service",
                "message": "order-db connection pool metric: active_connections=92/100 (92% pool utilization)",
                "metadata": {"active_connections": 92, "max_connections": 100},
            },
            {
                "offset_seconds": 30,
                "source": TelemetrySource.LOGS,
                "event_type": TelemetryEventType.LOG,
                "severity": "WARN",
                "service": "order-service",
                "message": "[WARN] order-db: Connection pool utilization reached 98/100. Pending connection wait queue: 45 callers",
                "metadata": {"active_connections": 98, "wait_queue_length": 45},
            },
            {
                "offset_seconds": 45,
                "source": TelemetrySource.DATABASE,
                "event_type": TelemetryEventType.DATABASE_EVENT,
                "severity": "ERROR",
                "service": "order-service",
                "message": "[ERROR] order-db: ConnectionTimeoutException - Timeout waiting for idle database connection after 5000ms",
                "metadata": {"exception": "ConnectionTimeoutException", "timeout_ms": 5000},
            },
            {
                "offset_seconds": 60,
                "source": TelemetrySource.LOGS,
                "event_type": TelemetryEventType.LOG,
                "severity": "ERROR",
                "service": "order-service",
                "message": "[ERROR] order-service: Failed to persist order #10492: org.postgresql.util.PSQLException: Connection pool exhausted",
                "metadata": {"order_id": "10492", "exception": "PSQLException"},
            },
            {
                "offset_seconds": 75,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "CRITICAL",
                "service": "order-service",
                "message": "order-service metric: HTTP 503 Service Unavailable rate spiked to 38.5%",
                "metadata": {"error_503_rate": 0.385},
            },
            {
                "offset_seconds": 90,
                "source": TelemetrySource.SERVICE,
                "event_type": TelemetryEventType.ALERT,
                "severity": "CRITICAL",
                "service": "order-service",
                "message": "ALERT TRIGGERED: DatabaseConnectionPoolExhausted on order-service (98% utilization)",
                "metadata": {"alert_name": "DatabaseConnectionPoolExhausted"},
            },
        ],
    ),
    SimulationScenario.MEMORY_LEAK: ScenarioData(
        incident_title="Memory Leak and Process Instability in analytics-processor",
        incident_description="JVM heap utilization steadily rose to 94.5% causing stop-the-world GC pauses and eventual OutOfMemoryErrors.",
        severity=Severity.HIGH,
        affected_service="analytics-processor",
        ground_truth=GroundTruth(
            category="memory",
            root_cause="Unbounded caching memory leak in analytics-processor leading to heap saturation, GC pauses, and OutOfMemoryErrors.",
            affected_service="analytics-processor",
            expected_evidence=["MEMORY_GROWTH", "HEAP_THRESHOLD_BREACH", "GC_PAUSE_SPIKE", "PROCESS_UNSTABLE"],
        ),
        telemetry_templates=[
            {
                "offset_seconds": 0,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "INFO",
                "service": "analytics-processor",
                "message": "analytics-processor heap metric: memory_used_mb=1850MB (46.2% of 4000MB heap limit)",
                "metadata": {"memory_used_mb": 1850, "heap_max_mb": 4000},
            },
            {
                "offset_seconds": 30,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "WARN",
                "service": "analytics-processor",
                "message": "analytics-processor heap metric: memory_used_mb=2950MB (73.7% of 4000MB heap limit)",
                "metadata": {"memory_used_mb": 2950, "heap_max_mb": 4000},
            },
            {
                "offset_seconds": 60,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "ERROR",
                "service": "analytics-processor",
                "message": "analytics-processor heap metric: memory_used_mb=3780MB (94.5% of 4000MB heap limit - Threshold 85% Exceeded)",
                "metadata": {"memory_used_mb": 3780, "heap_max_mb": 4000, "threshold_pct": 0.85},
            },
            {
                "offset_seconds": 75,
                "source": TelemetrySource.LOGS,
                "event_type": TelemetryEventType.LOG,
                "severity": "WARN",
                "service": "analytics-processor",
                "message": "[WARN] analytics-processor: JVM Garbage Collection pause took 4820ms (Stop-The-World)",
                "metadata": {"gc_pause_ms": 4820, "gc_type": "G1 Old Generation"},
            },
            {
                "offset_seconds": 90,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "ERROR",
                "service": "analytics-processor",
                "message": "analytics-processor metric: p99_latency increased from 350ms to 8900ms due to GC pressure",
                "metadata": {"p99_latency_ms": 8900, "baseline_ms": 350},
            },
            {
                "offset_seconds": 105,
                "source": TelemetrySource.LOGS,
                "event_type": TelemetryEventType.LOG,
                "severity": "CRITICAL",
                "service": "analytics-processor",
                "message": "[ERROR] analytics-processor: java.lang.OutOfMemoryError: Java heap space during event aggregation batch #482",
                "metadata": {"exception": "OutOfMemoryError", "detail": "Java heap space"},
            },
            {
                "offset_seconds": 120,
                "source": TelemetrySource.SERVICE,
                "event_type": TelemetryEventType.ALERT,
                "severity": "CRITICAL",
                "service": "analytics-processor",
                "message": "ALERT TRIGGERED: HeapMemoryLimitExceeded on analytics-processor (94.5% > 85.0%)",
                "metadata": {"alert_name": "HeapMemoryLimitExceeded"},
            },
        ],
    ),
    SimulationScenario.DEPENDENCY_FAILURE: ScenarioData(
        incident_title="Cascading Failures due to External Auth Provider Outage",
        incident_description="Checkout flow failures spiked to 42.1% due to connection timeouts and retry exhaustion against auth.external-api.com.",
        severity=Severity.HIGH,
        affected_service="checkout-service",
        ground_truth=GroundTruth(
            category="dependency",
            root_cause="External dependency auth.external-api.com returned HTTP 504 gateway timeouts causing retry exhaustion and cascading checkout failures.",
            affected_service="checkout-service",
            expected_evidence=["DEPENDENCY_UNAVAILABLE", "TIMEOUT_EVENTS", "RETRY_STORM", "CASCADING_ERRORS"],
        ),
        telemetry_templates=[
            {
                "offset_seconds": 0,
                "source": TelemetrySource.NETWORK,
                "event_type": TelemetryEventType.SERVICE_EVENT,
                "severity": "WARN",
                "service": "checkout-service",
                "message": "External dependency auth.external-api.com response latency increased from 45ms to 10000ms",
                "metadata": {"dependency": "auth.external-api.com", "latency_ms": 10000},
            },
            {
                "offset_seconds": 15,
                "source": TelemetrySource.LOGS,
                "event_type": TelemetryEventType.LOG,
                "severity": "ERROR",
                "service": "checkout-service",
                "message": "[ERROR] checkout-service: ConnectTimeoutException connecting to https://auth.external-api.com/v1/verify after 5000ms",
                "metadata": {"dependency": "auth.external-api.com", "exception": "ConnectTimeoutException"},
            },
            {
                "offset_seconds": 30,
                "source": TelemetrySource.LOGS,
                "event_type": TelemetryEventType.LOG,
                "severity": "WARN",
                "service": "checkout-service",
                "message": "[WARN] checkout-service: Retry 3/3 failed for auth verification token user_88392. Escalating dependency failure.",
                "metadata": {"dependency": "auth.external-api.com", "retry_count": 3, "max_retries": 3},
            },
            {
                "offset_seconds": 45,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "ERROR",
                "service": "checkout-service",
                "message": "checkout-service metric: outbound dependency error rate (auth.external-api.com) = 96.2%",
                "metadata": {"dependency": "auth.external-api.com", "dependency_error_rate": 0.962},
            },
            {
                "offset_seconds": 60,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "CRITICAL",
                "service": "checkout-service",
                "message": "checkout-service metric: checkout_flow_failure_rate increased to 42.1%",
                "metadata": {"failure_rate": 0.421},
            },
            {
                "offset_seconds": 75,
                "source": TelemetrySource.SERVICE,
                "event_type": TelemetryEventType.ALERT,
                "severity": "CRITICAL",
                "service": "checkout-service",
                "message": "ALERT TRIGGERED: DependencyUnavailable on auth.external-api.com (error rate 96.2%)",
                "metadata": {"alert_name": "DependencyUnavailable", "dependency": "auth.external-api.com"},
            },
        ],
    ),
    SimulationScenario.TRAFFIC_SPIKE: ScenarioData(
        incident_title="Service Degradation under 5x Sudden Traffic Surge",
        incident_description="Sudden 5x traffic surge resulted in 96.8% host CPU utilization, thread pool queue backlog, and elevated latency.",
        severity=Severity.MEDIUM,
        affected_service="user-feed-service",
        ground_truth=GroundTruth(
            category="traffic",
            root_cause="Unanticipated 5x traffic surge causing host CPU saturation, worker queue backlog, and elevated latency on user-feed-service.",
            affected_service="user-feed-service",
            expected_evidence=["TRAFFIC_SURGE", "CPU_SATURATION", "QUEUE_BACKLOG", "LATENCY_SPIKE"],
        ),
        telemetry_templates=[
            {
                "offset_seconds": 0,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "INFO",
                "service": "user-feed-service",
                "message": "user-feed-service metric: request_rate jumped from 1200 req/sec to 6200 req/sec (5.1x traffic spike)",
                "metadata": {"request_rate": 6200, "baseline_rate": 1200, "multiplier": 5.1},
            },
            {
                "offset_seconds": 15,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "WARN",
                "service": "user-feed-service",
                "message": "user-feed-service host metric: CPU utilization reached 96.8% (threshold: 80%)",
                "metadata": {"cpu_utilization": 0.968, "threshold": 0.80},
            },
            {
                "offset_seconds": 30,
                "source": TelemetrySource.LOGS,
                "event_type": TelemetryEventType.LOG,
                "severity": "WARN",
                "service": "user-feed-service",
                "message": "[WARN] user-feed-service: Worker thread pool queue size reached 850 items (capacity 1000)",
                "metadata": {"queue_size": 850, "capacity": 1000},
            },
            {
                "offset_seconds": 45,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "WARN",
                "service": "user-feed-service",
                "message": "user-feed-service metric: p95_latency degraded from 85ms to 1420ms",
                "metadata": {"p95_latency_ms": 1420, "baseline_ms": 85},
            },
            {
                "offset_seconds": 60,
                "source": TelemetrySource.METRICS,
                "event_type": TelemetryEventType.METRIC,
                "severity": "ERROR",
                "service": "user-feed-service",
                "message": "user-feed-service metric: error_rate increased to 5.4% (HTTP 504 Gateway Timeout)",
                "metadata": {"error_rate": 0.054, "error_type": "HTTP 504"},
            },
            {
                "offset_seconds": 75,
                "source": TelemetrySource.SERVICE,
                "event_type": TelemetryEventType.ALERT,
                "severity": "WARN",
                "service": "user-feed-service",
                "message": "ALERT TRIGGERED: HighCpuAndLatency on user-feed-service (CPU 96.8%, Latency 1420ms)",
                "metadata": {"alert_name": "HighCpuAndLatency"},
            },
        ],
    ),
}
